
import javax.swing.JFrame;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mMenuBar = new javax.swing.JMenuBar();
        mArquivo = new javax.swing.JMenu();
        mItemNovo = new javax.swing.JMenuItem();
        mItemSair = new javax.swing.JMenuItem();
        mRelatorio = new javax.swing.JMenu();
        mMenuCliente = new javax.swing.JMenuItem();
        mMenuFornecedor = new javax.swing.JMenuItem();
        mSobre = new javax.swing.JMenu();
        mMenuInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU, ITENS DE MENU, FONTES");

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONTROLE DE CLIENTES");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aluno\\Desktop\\logo-unifagoc.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(110, 110, 110))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        mArquivo.setText("Arquivo");
        mArquivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mArquivoItemStateChanged(evt);
            }
        });

        mItemNovo.setText("Novo");
        mItemNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemNovoActionPerformed(evt);
            }
        });
        mArquivo.add(mItemNovo);

        mItemSair.setText("Sair");
        mItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSairActionPerformed(evt);
            }
        });
        mArquivo.add(mItemSair);

        mMenuBar.add(mArquivo);

        mRelatorio.setText("Relatório");

        mMenuCliente.setText("Cliente");
        mMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMenuClienteActionPerformed(evt);
            }
        });
        mRelatorio.add(mMenuCliente);

        mMenuFornecedor.setText("Fornecedor");
        mMenuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMenuFornecedorActionPerformed(evt);
            }
        });
        mRelatorio.add(mMenuFornecedor);

        mMenuBar.add(mRelatorio);

        mSobre.setText("Sobre");

        mMenuInfo.setText("Info");
        mMenuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMenuInfoActionPerformed(evt);
            }
        });
        mSobre.add(mMenuInfo);

        mMenuBar.add(mSobre);

        setJMenuBar(mMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mArquivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mArquivoItemStateChanged

    }//GEN-LAST:event_mArquivoItemStateChanged

    private void mItemNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemNovoActionPerformed
        FormCadastroAlubo formCadastro = new FormCadastroAlubo();
        formCadastro.setVisible(true);
    }//GEN-LAST:event_mItemNovoActionPerformed

    private void mItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mItemSairActionPerformed

    private void mMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMenuClienteActionPerformed
       JOptionPane.showMessageDialog(rootPane, "Relatório de Clientes");
    }//GEN-LAST:event_mMenuClienteActionPerformed

    private void mMenuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMenuFornecedorActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Relatório de Fornecedores");
    }//GEN-LAST:event_mMenuFornecedorActionPerformed

    private void mMenuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMenuInfoActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Nome do Aluno: João Pedro Vidal dos Santos");
        FormCadastroAlubo formCadastro = new FormCadastroAlubo();
        this.dispose();
    }//GEN-LAST:event_mMenuInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mArquivo;
    private javax.swing.JMenuItem mItemNovo;
    private javax.swing.JMenuItem mItemSair;
    private javax.swing.JMenuBar mMenuBar;
    private javax.swing.JMenuItem mMenuCliente;
    private javax.swing.JMenuItem mMenuFornecedor;
    private javax.swing.JMenuItem mMenuInfo;
    private javax.swing.JMenu mRelatorio;
    private javax.swing.JMenu mSobre;
    // End of variables declaration//GEN-END:variables
}
